const sampleListings = [
    {
        title: "Cozy Beachfront Cottage",
        description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning views of the ocean and the sound of waves.",
        image: "https://images.unsplash.com/photo-1",
        price: 1500,
        location: "Malibu",
        country: "United States",
    },
    {
        title: "Modern City Apartment",
        description: "Stylish apartment in the heart of downtown. Perfect for business travelers or city explorers.",
        image: "https://images.unsplash.com/photo-2",
        price: 950,
        location: "New York City",
        country: "United States",
    },
    {
        title: "Rustic Mountain Cabin",
        description: "Get away from it all in this peaceful mountain cabin. Ideal for hikers and nature lovers.",
        image: "https://images.unsplash.com/photo-3",
        price: 800,
        location: "Aspen",
        country: "United States",
    },
    {
        title: "Luxurious Paris Flat",
        description: "Experience the romance of Paris from this luxurious flat near the Eiffel Tower.",
        image: "https://images.unsplash.com/photo-4",
        price: 2000,
        location: "Paris",
        country: "France",
    },
    {
        title: "Traditional Japanese Ryokan",
        description: "Stay in a traditional Japanese inn with tatami mats and hot springs in Kyoto.",
        image: "https://images.unsplash.com/photo-5",
        price: 1100,
        location: "Kyoto",
        country: "Japan",
    },
    {
        title: "Santorini Cliffside Villa",
        description: "Marvel at breathtaking sunsets from this cliffside villa overlooking the Aegean Sea.",
        image: "https://images.unsplash.com/photo-6",
        price: 1800,
        location: "Santorini",
        country: "Greece",
    },
    {
        title: "Safari Lodge in Kenya",
        description: "Adventure awaits in this eco-friendly lodge surrounded by wildlife in the Masai Mara.",
        image: "https://images.unsplash.com/photo-7",
        price: 1700,
        location: "Masai Mara",
        country: "Kenya",
    },
    {
        title: "Chic Barcelona Loft",
        description: "Enjoy modern living in this artsy loft close to Gaudi’s famous landmarks.",
        image: "https://images.unsplash.com/photo-8",
        price: 1200,
        location: "Barcelona",
        country: "Spain",
    },
    {
        title: "Icelandic Glass Cabin",
        description: "Watch the northern lights from your bed in this secluded glass cabin in Iceland.",
        image: "https://images.unsplash.com/photo-9",
        price: 1600,
        location: "Reykjavik",
        country: "Iceland",
    },
    {
        title: "Desert Dome in Dubai",
        description: "A futuristic dome stay in the Dubai desert with luxury amenities and starry skies.",
        image: "https://images.unsplash.com/photo-10",
        price: 1900,
        location: "Dubai",
        country: "United Arab Emirates",
    }
];

module.exports={data:sampleListings};